sama jama ikka.    Error CS0234: The type or namespace name 'Models' does not exist in the namespace 'SooduskorvWebMVC' (are you missing an assembly reference?) (1, 1)     Error CS0234: The type or namespace name 'Models' does not exist in the namespace 'SooduskorvWebMVC' (are you missing an assembly reference?) (1, 1)     Error CS0234: The type or namespace name 'Models' does not exist in the namespace 'SooduskorvWebMVC' (are you missing an assembly reference?) (1, 1)